[
  {
    "date": "2026-04-18",
    "league": "Serie A",
    "home": "AS Roma",
    "away": "Atalanta",
    "market": "OU35",
    "pick": "U3.5",
    "prob": 82,
    "odds": 1.32,
    "value": 6.2,
    "ens_raw": 90,
    "book_prob": 73.5,
    "ois": 0,
    "edge_type": "moderate_edge",
    "regime": "live",
    "model_agreement": 82,
    "implied_vol": 5,
    "inj_h": 15,
    "inj_a": 12,
    "system": "v5_high",
    "in_schedina": false,
    "schedina": null,
    "season_phase": "mid_season",
    "season_week": null,
    "european_week": false,
    "post_international_break": false,
    "month": 4,
    "result": {
      "home_goals": 1,
      "away_goals": 1,
      "ht_home": 1,
      "ht_away": 1,
      "won": true,
      "profit": 1.6
    }
  },
  {
    "date": "2026-04-18",
    "league": "Championship",
    "home": "Bristol City",
    "away": "Norwich",
    "market": "OU15",
    "pick": "O1.5",
    "prob": 82,
    "odds": 1.3,
    "value": 5.1,
    "ens_raw": 86.8,
    "book_prob": 74.6,
    "ois": 0,
    "edge_type": "moderate_edge",
    "regime": "live",
    "model_agreement": 82,
    "implied_vol": 5,
    "inj_h": 15,
    "inj_a": 15,
    "system": "v5_high",
    "in_schedina": false,
    "schedina": null,
    "season_phase": "mid_season",
    "season_week": null,
    "european_week": false,
    "post_international_break": false,
    "month": 4,
    "result": {
      "home_goals": 2,
      "away_goals": 4,
      "ht_home": 1,
      "ht_away": 0,
      "won": true,
      "profit": 1.5
    }
  },
  {
    "date": "2026-04-18",
    "league": "Championship",
    "home": "Sheffield Wednesday",
    "away": "Charlton",
    "market": "OU35",
    "pick": "U3.5",
    "prob": 82,
    "odds": 1.26,
    "value": 2.6,
    "ens_raw": 90,
    "book_prob": 77.0,
    "ois": 0,
    "edge_type": "moderate_edge",
    "regime": "live",
    "model_agreement": 82,
    "implied_vol": 5,
    "inj_h": 15,
    "inj_a": 15,
    "system": "v5_high",
    "in_schedina": false,
    "schedina": null,
    "season_phase": "mid_season",
    "season_week": null,
    "european_week": false,
    "post_international_break": false,
    "month": 4,
    "result": {
      "home_goals": 1,
      "away_goals": 1,
      "ht_home": 0,
      "ht_away": 0,
      "won": true,
      "profit": 1.3
    }
  },
  {
    "date": "2026-04-18",
    "league": "Premier League",
    "home": "Leeds",
    "away": "Wolves",
    "market": "OU35",
    "pick": "U3.5",
    "prob": 82,
    "odds": 1.34,
    "value": 7.4,
    "ens_raw": 89.9,
    "book_prob": 72.4,
    "ois": 0,
    "edge_type": "moderate_edge",
    "regime": "live",
    "model_agreement": 82,
    "implied_vol": 5,
    "inj_h": 15,
    "inj_a": 15,
    "system": "v5_high",
    "in_schedina": false,
    "schedina": null,
    "season_phase": "mid_season",
    "season_week": null,
    "european_week": false,
    "post_international_break": false,
    "month": 4,
    "result": {
      "home_goals": 3,
      "away_goals": 0,
      "ht_home": 2,
      "ht_away": 0,
      "won": true,
      "profit": 1.7
    }
  },
  {
    "date": "2026-04-18",
    "league": "Premier League",
    "home": "Tottenham",
    "away": "Brighton",
    "market": "OU35",
    "pick": "U3.5",
    "prob": 82,
    "odds": 1.45,
    "value": 13.0,
    "ens_raw": 85.5,
    "book_prob": 66.9,
    "ois": 0,
    "edge_type": "value",
    "regime": "live",
    "model_agreement": 82,
    "implied_vol": 5,
    "inj_h": 15,
    "inj_a": 15,
    "system": "v5_high",
    "in_schedina": true,
    "schedina": "schedina_1_2026-04-18",
    "season_phase": "mid_season",
    "season_week": null,
    "european_week": false,
    "post_international_break": false,
    "month": 4,
    "result": {
      "home_goals": 2,
      "away_goals": 2,
      "ht_home": 1,
      "ht_away": 1,
      "won": false,
      "profit": -5.0
    }
  },
  {
    "date": "2026-04-18",
    "league": "Premier League",
    "home": "Chelsea",
    "away": "Manchester United",
    "market": "G1T",
    "pick": "G1T_Y",
    "prob": 82,
    "odds": 1.26,
    "value": 2.6,
    "ens_raw": 78,
    "book_prob": 77.0,
    "ois": 0,
    "edge_type": "moderate_edge",
    "regime": "live",
    "model_agreement": 82,
    "implied_vol": 5,
    "inj_h": 15,
    "inj_a": 15,
    "system": "v5_high",
    "in_schedina": true,
    "schedina": "schedina_2_2026-04-18",
    "season_phase": "mid_season",
    "season_week": null,
    "european_week": false,
    "post_international_break": false,
    "month": 4,
    "result": {
      "home_goals": 0,
      "away_goals": 1,
      "ht_home": 0,
      "ht_away": 1,
      "won": true,
      "profit": 1.3
    }
  },
  {
    "date": "2026-04-18",
    "league": "Championship",
    "home": "Hull City",
    "away": "Birmingham",
    "market": "OU35",
    "pick": "U3.5",
    "prob": 81.4,
    "odds": 1.31,
    "value": 5.1,
    "ens_raw": 90,
    "book_prob": 74.0,
    "ois": 0,
    "edge_type": "moderate_edge",
    "regime": "live",
    "model_agreement": 81.0,
    "implied_vol": 5,
    "inj_h": 15,
    "inj_a": 12,
    "system": "v5_high",
    "in_schedina": false,
    "schedina": null,
    "season_phase": "mid_season",
    "season_week": null,
    "european_week": false,
    "post_international_break": false,
    "month": 4,
    "result": {
      "home_goals": 1,
      "away_goals": 1,
      "ht_home": 1,
      "ht_away": 0,
      "won": true,
      "profit": 1.55
    }
  },
  {
    "date": "2026-04-18",
    "league": "Serie B",
    "home": "Palermo",
    "away": "Cesena",
    "market": "OU35",
    "pick": "U3.5",
    "prob": 81.3,
    "odds": 1.41,
    "value": 10.4,
    "ens_raw": 83.4,
    "book_prob": 68.8,
    "ois": 0,
    "edge_type": "value",
    "regime": "live",
    "model_agreement": 81.0,
    "implied_vol": 5,
    "inj_h": 0,
    "inj_a": 0,
    "system": "v5_high",
    "in_schedina": false,
    "schedina": null,
    "season_phase": "mid_season",
    "season_week": null,
    "european_week": false,
    "post_international_break": false,
    "month": 4,
    "result": {
      "home_goals": 2,
      "away_goals": 0,
      "ht_home": 1,
      "ht_away": 0,
      "won": true,
      "profit": 2.05
    }
  },
  {
    "date": "2026-04-18",
    "league": "Serie B",
    "home": "Modena",
    "away": "Frosinone",
    "market": "OU35",
    "pick": "U3.5",
    "prob": 80.8,
    "odds": 1.44,
    "value": 11.4,
    "ens_raw": 90,
    "book_prob": 67.4,
    "ois": 0,
    "edge_type": "value",
    "regime": "live",
    "model_agreement": 81.0,
    "implied_vol": 5,
    "inj_h": 0,
    "inj_a": 0,
    "system": "v5_high",
    "in_schedina": false,
    "schedina": null,
    "season_phase": "mid_season",
    "season_week": null,
    "european_week": false,
    "post_international_break": false,
    "month": 4,
    "result": {
      "home_goals": 1,
      "away_goals": 2,
      "ht_home": 1,
      "ht_away": 0,
      "won": true,
      "profit": 2.2
    }
  },
  {
    "date": "2026-04-18",
    "league": "Championship",
    "home": "Derby",
    "away": "Oxford United",
    "market": "OU35",
    "pick": "U3.5",
    "prob": 80.6,
    "odds": 1.28,
    "value": 2.5,
    "ens_raw": 86.2,
    "book_prob": 75.8,
    "ois": 0,
    "edge_type": "moderate_edge",
    "regime": "live",
    "model_agreement": 81.0,
    "implied_vol": 5,
    "inj_h": 15,
    "inj_a": 15,
    "system": "v5_high",
    "in_schedina": false,
    "schedina": null,
    "season_phase": "mid_season",
    "season_week": null,
    "european_week": false,
    "post_international_break": false,
    "month": 4,
    "result": {
      "home_goals": 1,
      "away_goals": 0,
      "ht_home": 1,
      "ht_away": 0,
      "won": true,
      "profit": 1.4
    }
  },
  {
    "date": "2026-04-18",
    "league": "Championship",
    "home": "Watford",
    "away": "Sheffield Utd",
    "market": "OU35",
    "pick": "U3.5",
    "prob": 80.3,
    "odds": 1.38,
    "value": 7.8,
    "ens_raw": 88.8,
    "book_prob": 70.3,
    "ois": 0,
    "edge_type": "moderate_edge",
    "regime": "live",
    "model_agreement": 80.0,
    "implied_vol": 5,
    "inj_h": 15,
    "inj_a": 15,
    "system": "v5_high",
    "in_schedina": true,
    "schedina": "schedina_1_2026-04-18",
    "season_phase": "mid_season",
    "season_week": null,
    "european_week": false,
    "post_international_break": false,
    "month": 4,
    "result": {
      "home_goals": 0,
      "away_goals": 2,
      "ht_home": 0,
      "ht_away": 0,
      "won": true,
      "profit": 1.9
    }
  },
  {
    "date": "2026-04-18",
    "league": "Serie B",
    "home": "Mantova",
    "away": "Avellino",
    "market": "OU15",
    "pick": "O1.5",
    "prob": 79.0,
    "odds": 1.33,
    "value": 3.9,
    "ens_raw": 77.7,
    "book_prob": 72.9,
    "ois": 0,
    "edge_type": "moderate_edge",
    "regime": "live",
    "model_agreement": 79.0,
    "implied_vol": 5,
    "inj_h": 0,
    "inj_a": 0,
    "system": "v5_high",
    "in_schedina": false,
    "schedina": null,
    "season_phase": "mid_season",
    "season_week": null,
    "european_week": false,
    "post_international_break": false,
    "month": 4,
    "result": {
      "home_goals": 0,
      "away_goals": 2,
      "ht_home": 0,
      "ht_away": 0,
      "won": true,
      "profit": 1.65
    }
  },
  {
    "date": "2026-04-18",
    "league": "Serie B",
    "home": "Bari",
    "away": "Venezia",
    "market": "OU35",
    "pick": "U3.5",
    "prob": 78.8,
    "odds": 1.52,
    "value": 13.0,
    "ens_raw": 82.3,
    "book_prob": 63.8,
    "ois": 0,
    "edge_type": "value",
    "regime": "live",
    "model_agreement": 79.0,
    "implied_vol": 5,
    "inj_h": 0,
    "inj_a": 0,
    "system": "v5_high",
    "in_schedina": true,
    "schedina": "schedina_1_2026-04-18",
    "season_phase": "mid_season",
    "season_week": null,
    "european_week": false,
    "post_international_break": false,
    "month": 4,
    "result": {
      "home_goals": 0,
      "away_goals": 3,
      "ht_home": 0,
      "ht_away": 2,
      "won": true,
      "profit": 2.6
    }
  },
  {
    "date": "2026-04-18",
    "league": "Serie B",
    "home": "Modena",
    "away": "Frosinone",
    "market": "G1T",
    "pick": "G1T_Y",
    "prob": 78.2,
    "odds": 1.32,
    "value": 2.4,
    "ens_raw": 76.5,
    "book_prob": 73.5,
    "ois": 0,
    "edge_type": "moderate_edge",
    "regime": "live",
    "model_agreement": 78.0,
    "implied_vol": 5,
    "inj_h": 0,
    "inj_a": 0,
    "system": "v5_high",
    "in_schedina": false,
    "schedina": null,
    "season_phase": "mid_season",
    "season_week": null,
    "european_week": false,
    "post_international_break": false,
    "month": 4,
    "result": {
      "home_goals": 1,
      "away_goals": 2,
      "ht_home": 1,
      "ht_away": 0,
      "won": true,
      "profit": 1.6
    }
  },
  {
    "date": "2026-04-18",
    "league": "Championship",
    "home": "Bristol City",
    "away": "Norwich",
    "market": "G1T",
    "pick": "G1T_Y",
    "prob": 77.2,
    "odds": 1.39,
    "value": 5.3,
    "ens_raw": 75.0,
    "book_prob": 69.8,
    "ois": 0,
    "edge_type": "moderate_edge",
    "regime": "live",
    "model_agreement": 77.0,
    "implied_vol": 5,
    "inj_h": 15,
    "inj_a": 15,
    "system": "v5_high",
    "in_schedina": true,
    "schedina": "schedina_2_2026-04-18",
    "season_phase": "mid_season",
    "season_week": null,
    "european_week": false,
    "post_international_break": false,
    "month": 4,
    "result": {
      "home_goals": 2,
      "away_goals": 4,
      "ht_home": 1,
      "ht_away": 0,
      "won": true,
      "profit": 1.95
    }
  },
  {
    "date": "2026-04-18",
    "league": "Serie B",
    "home": "Juve Stabia",
    "away": "Catanzaro",
    "market": "G1T",
    "pick": "G1T_Y",
    "prob": 76.4,
    "odds": 1.42,
    "value": 6.0,
    "ens_raw": 76.5,
    "book_prob": 68.3,
    "ois": 0,
    "edge_type": "moderate_edge",
    "regime": "live",
    "model_agreement": 76.0,
    "implied_vol": 5,
    "inj_h": 0,
    "inj_a": 0,
    "system": "v5_high",
    "in_schedina": true,
    "schedina": "schedina_2_2026-04-18",
    "season_phase": "mid_season",
    "season_week": null,
    "european_week": false,
    "post_international_break": false,
    "month": 4,
    "result": {
      "home_goals": 1,
      "away_goals": 1,
      "ht_home": 1,
      "ht_away": 0,
      "won": true,
      "profit": 2.1
    }
  },
  {
    "date": "2026-04-18",
    "league": "Serie B",
    "home": "Mantova",
    "away": "Avellino",
    "market": "G1T",
    "pick": "G1T_Y",
    "prob": 75.7,
    "odds": 1.42,
    "value": 5.2,
    "ens_raw": 73.5,
    "book_prob": 68.3,
    "ois": 0,
    "edge_type": "moderate_edge",
    "regime": "live",
    "model_agreement": 76.0,
    "implied_vol": 5,
    "inj_h": 0,
    "inj_a": 0,
    "system": "v5_high",
    "in_schedina": false,
    "schedina": null,
    "season_phase": "mid_season",
    "season_week": null,
    "european_week": false,
    "post_international_break": false,
    "month": 4,
    "result": {
      "home_goals": 0,
      "away_goals": 2,
      "ht_home": 0,
      "ht_away": 0,
      "won": false,
      "profit": -5.0
    }
  },
  {
    "date": "2026-04-18",
    "league": "Championship",
    "home": "Wrexham",
    "away": "Stoke City",
    "market": "OU35",
    "pick": "U3.5",
    "prob": 74.3,
    "odds": 1.4,
    "value": 2.8,
    "ens_raw": 81.6,
    "book_prob": 69.3,
    "ois": 0,
    "edge_type": "moderate_edge",
    "regime": "live",
    "model_agreement": 74.0,
    "implied_vol": 5,
    "inj_h": 15,
    "inj_a": 15,
    "system": "v5_high",
    "in_schedina": false,
    "schedina": null,
    "season_phase": "mid_season",
    "season_week": null,
    "european_week": false,
    "post_international_break": false,
    "month": 4,
    "result": {
      "home_goals": 2,
      "away_goals": 0,
      "ht_home": 2,
      "ht_away": 0,
      "won": true,
      "profit": 2.0
    }
  },
  {
    "date": "2026-04-18",
    "league": "Serie A",
    "home": "AS Roma",
    "away": "Atalanta",
    "market": "G1T",
    "pick": "G1T_Y",
    "prob": 73.5,
    "odds": 1.4,
    "value": 2.1,
    "ens_raw": 69.7,
    "book_prob": 69.3,
    "ois": 0,
    "edge_type": "moderate_edge",
    "regime": "live",
    "model_agreement": 74.0,
    "implied_vol": 5,
    "inj_h": 15,
    "inj_a": 12,
    "system": "v5_high",
    "in_schedina": false,
    "schedina": null,
    "season_phase": "mid_season",
    "season_week": null,
    "european_week": false,
    "post_international_break": false,
    "month": 4,
    "result": {
      "home_goals": 1,
      "away_goals": 1,
      "ht_home": 1,
      "ht_away": 1,
      "won": true,
      "profit": 2.0
    }
  },
  {
    "date": "2026-04-18",
    "league": "Championship",
    "home": "Portsmouth",
    "away": "Leicester",
    "market": "G1T",
    "pick": "G1T_Y",
    "prob": 72.8,
    "odds": 1.46,
    "value": 4.3,
    "ens_raw": 78,
    "book_prob": 66.4,
    "ois": 0,
    "edge_type": "moderate_edge",
    "regime": "live",
    "model_agreement": 73.0,
    "implied_vol": 5,
    "inj_h": 15,
    "inj_a": 12,
    "system": "v5_high",
    "in_schedina": false,
    "schedina": null,
    "season_phase": "mid_season",
    "season_week": null,
    "european_week": false,
    "post_international_break": false,
    "month": 4,
    "result": {
      "home_goals": 1,
      "away_goals": 0,
      "ht_home": 0,
      "ht_away": 0,
      "won": false,
      "profit": -5.0
    }
  },
  {
    "date": "2026-04-18",
    "league": "Serie A",
    "home": "Udinese",
    "away": "Parma",
    "market": "G1T",
    "pick": "G1T_Y",
    "prob": 71.2,
    "odds": 1.5,
    "value": 4.6,
    "ens_raw": 68.6,
    "book_prob": 64.7,
    "ois": 0,
    "edge_type": "moderate_edge",
    "regime": "live",
    "model_agreement": 71.0,
    "implied_vol": 5,
    "inj_h": 15,
    "inj_a": 12,
    "system": "v5_high",
    "in_schedina": true,
    "schedina": "schedina_2_2026-04-18",
    "season_phase": "mid_season",
    "season_week": null,
    "european_week": false,
    "post_international_break": false,
    "month": 4,
    "result": {
      "home_goals": 0,
      "away_goals": 1,
      "ht_home": 0,
      "ht_away": 0,
      "won": false,
      "profit": -5.0
    }
  },
  {
    "date": "2026-04-18",
    "league": "Bundesliga",
    "home": "Werder Bremen",
    "away": "Hamburger SV",
    "market": "DC",
    "pick": "X2",
    "prob": 60.4,
    "odds": 1.84,
    "value": 6.0,
    "ens_raw": 71.5,
    "book_prob": 52.7,
    "ois": 0,
    "edge_type": "moderate_edge",
    "regime": "live",
    "model_agreement": 60.0,
    "implied_vol": 5,
    "inj_h": 15,
    "inj_a": 15,
    "system": "v5_high",
    "in_schedina": false,
    "schedina": null,
    "season_phase": "mid_season",
    "season_week": null,
    "european_week": false,
    "post_international_break": false,
    "month": 4,
    "result": {
      "home_goals": 3,
      "away_goals": 1,
      "ht_home": 1,
      "ht_away": 1,
      "won": false,
      "profit": -5.0
    }
  }
]
